## intro

In [1]:
import numpy as np

In [2]:
test_array=np.array([1,4,5,8],float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [3]:
test_array

array([1., 4., 5., 8.])

In [4]:
test_array2 = np.array(["1", 4, "5", 8],float)
test_array2
'''
파이썬 >> dynamic typing >> 실행 시점에 데이터 타입을 결정함
>> 하나의 리스트에 다양한 데이터 타입이 들어갈 수 있음

반면, numpy는 이런 것을 허락하지 않음.(하나의 데이터 타입만 배열에 넣을 수 있음)
array의 []내부에 int, str 타입의 데이터를 넣었지만,
뒤에 array의 타입을 float으로 정했기 때문에 모든 데이터 타입이 float으로 바뀜.

'''

'\n파이썬 >> dynamic typing >> 실행 시점에 데이터 타입을 결정함\n>> 하나의 리스트에 다양한 데이터 타입이 들어갈 수 있음\n\n반면, numpy는 이런 것을 허락하지 않음.(하나의 데이터 타입만 배열에 넣을 수 있음)\narray의 []내부에 int, str 타입의 데이터를 넣었지만,\n뒤에 array의 타입을 float으로 정했기 때문에 모든 데이터 타입이 float으로 바뀜.\n\n'

In [5]:
print(type(test_array2[2]))
'''
float64의 64는 데이터의 메모리 공간의 크기를 의미함.
float32의 경우 32bit=4byte의 메모리 공간을 가짐.
test_array2의 경우 64bit=8byte의 메모리 공간을 차지하는 데이터가 4개 있으므로
 총 32byte 공간을 차지함.
'''

<class 'numpy.float64'>


'\nfloat64의 64는 데이터의 메모리 공간의 크기를 의미함.\nfloat32의 경우 32bit=4byte의 메모리 공간을 가짐.\ntest_array2의 경우 64bit=8byte의 메모리 공간을 차지하는 데이터가 4개 있으므로\n 총 32byte 공간을 차지함.\n'

In [6]:
test_array3 = np.array(["1", 4, "5", 8],np.float32)

In [7]:
test_array3.dtype

dtype('float32')

In [8]:
test_array.dtype

dtype('float64')

In [9]:
test_array.shape  # Array의 shape을 반환함 (1차원 배열의 경우 1개 원소를 가진 튜플형식으로 표현됨)

(4,)

In [10]:
test_array_1=np.array([[1,4,5,8]],float)

In [11]:
test_array_1.shape # [[]]은 2차원 배열이므로 (행,열)형태로 계산됨

(1, 4)

In [12]:
test_array_1.dtype

dtype('float64')

In [13]:
test_array4=np.array([[[1,4,5,8],[0, 0 ,0, 0]],[[1,4,5,8],[0, 0, 0, 0]],[[1,4,5,8],[0, 0 ,0, 0]],[[1,4,5,8],[0, 0, 0, 0]]],float)

In [14]:
print(test_array4)
test_array4.shape  # 3차원 배열의 경우 (깊이, 행, 열) 순으로 표현됨

# 4차원 배열을 입력한다면 새로운 변수는 앞자리에 추가됨 (NEW ,깊이, 행, 열)
# 5차원 이상도 마찬가지.

[[[1. 4. 5. 8.]
  [0. 0. 0. 0.]]

 [[1. 4. 5. 8.]
  [0. 0. 0. 0.]]

 [[1. 4. 5. 8.]
  [0. 0. 0. 0.]]

 [[1. 4. 5. 8.]
  [0. 0. 0. 0.]]]


(4, 2, 4)

In [15]:
test_array4.ndim # 텐서의 차원을 구함. 3차원.

3

In [16]:
test_array4.size # 텐서의 크기를 구함. 4*2*4=32개의 원소를 가지고 있음.

32

## reshape

In [17]:
# 주로 백터를 행렬형태로 바꿀 때 사용함.
test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [18]:
np.array(test_matrix).reshape(2,2,2) # 2*4 = 2*2*2 = 8

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
np.array(test_matrix).reshape(8).shape

(8,)

In [20]:
np.array(test_matrix).reshape(-1,2).shape # size 기반으로 row 개수 선정.
# 행은 몇인지 정확히 모르지만 열은 2열로 고정하고 싶을 때 사용하면 알아서 반환해줌.

(4, 2)

## flatten
##### 다차원 array를 1차원 array로 변환

In [21]:
F_array=np.array(test_matrix, int).flatten()

In [22]:
F_array

array([1, 2, 3, 4, 5, 6, 7, 8])

## indexing
##### 이차원 배열에서 [0,0] 과 같은 표기법을 제공.

In [23]:
a= np.array([[1,3,5],[2,4,6]],int)
print(a)
print(a[0,2])
print(a[0][2])

[[1 3 5]
 [2 4 6]]
5
5


## slicing
##### List와 달리 행과 열 부분을 나눠서 slicing이 가능함

In [24]:
# 행렬의 부분집합을 추출할 때 유용하게 사용된다.
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [25]:
test_exmaple[:,1:3] 

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [26]:
test_exmaple[1,:2]

array([1, 2])

In [27]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [28]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [29]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [30]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])